force-app/main/default/objects/Account/fields/TestObject3__c.field-meta.xml
<CustomField>
    <fullName>TestObject3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TestObject3</label>
    <referenceTo>TestObject3__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestObject1__c/TestObject1__c.object-meta.xml
<CustomObject>
    <label>TestObject1</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>TestObject1 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TestObject1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestObject1__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TestObject1</relationshipLabel>
    <relationshipName>TestObject1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestObject1__c/fields/TestObject3__c.field-meta.xml
<CustomField>
    <fullName>TestObject3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TestObject3</label>
    <referenceTo>TestObject3__c</referenceTo>
    <relationshipLabel>TestObject1</relationshipLabel>
    <relationshipName>TestObject1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestObject2__c/TestObject2__c.object-meta.xml
<CustomObject>
    <label>TestObject2</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>TestObject2 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TestObject2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestObject2__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TestObject2</relationshipLabel>
    <relationshipName>TestObject2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestObject2__c/fields/TestObject1__c.field-meta.xml
<CustomField>
    <fullName>TestObject1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TestObject1</label>
    <referenceTo>TestObject1__c</referenceTo>
    <relationshipLabel>TestObject2</relationshipLabel>
    <relationshipName>TestObject2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestObject3__c/TestObject3__c.object-meta.xml
<CustomObject>
    <label>TestObject3</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>TestObject3 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TestObject3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestObject3__c/fields/TestObject2__c.field-meta.xml
<CustomField>
    <fullName>TestObject2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TestObject2</label>
    <referenceTo>TestObject2__c</referenceTo>
    <relationshipLabel>TestObject3</relationshipLabel>
    <relationshipName>TestObject3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestObjectsHelper.cls
public with sharing class TestObjectsHelper {
    public TestObjectsHelper() {

    }

    public List<TestObject3__c> createTestObjects(List<Account> accs) {
        Integer length = accs.size();
        List<TestObject1__c> to1 = new List<TestObject1__c>();
        List<TestObject2__c> to2 = new List<TestObject2__c>();
        List<TestObject3__c> to3 = new List<TestObject3__c>();
        for (Integer i = 0; i < length; i++) {
            to1.add(buildTestObject1(accs.get(i)));
        }
        insert to1;
        for (Integer i = 0; i < length; i++) {
            to2.add(buildTestObject2(accs.get(i), to1.get(i)));
        }
        insert to2;
        for (Integer i = 0; i < length; i++) {
            to3.add(buildTestObject3(to2.get(i)));
        }
        insert to3;
        for (Integer i = 0; i < length; i++) {
            to1.get(i).TestObject3__c = to3.get(i).Id;
        }
        update to1;

        return to3;
    }

    private TestObject1__c buildTestObject1(Account acc) {
        TestObject1__c to1 = new TestObject1__c(
            Account__c = acc.Id
        );
        return to1;
    }

    private TestObject2__c buildTestObject2(Account acc, TestObject1__c to1) {
        TestObject2__c to2 = new TestObject2__c(
            Account__c = acc.Id,
            TestObject1__c = to1.Id
        );
        return to2;
    }

    private TestObject3__c buildTestObject3(TestObject2__c to2) {
        TestObject3__c to3 = new TestObject3__c(
            TestObject2__c = to2.Id
        );
        return to3;
    }



}